export default {
//GAME STATE
  tutorialStep: 0,
  scene: "INIT",
  currentRoom: 0,
  isOnDialog: false,
  endGame: false,
  found: false,
  locations:[],
  tips: [],
  acusation: false,
//DIALOG
  dialogHistory: [],
  dialogStep: 0,
  totalDialogSteps: 2,
  questionsByStep: 2,
  currentChar: null,
  questions: [],
  targetName: 'Juslecino',
  correct: 0,
  ncorrect: 0,
  correctMinimum: 2,
  gameEndState: null,
  tries: 0,
  score: 0,
  startedTimestamp: new Date(Date.now()),
  elapsedTime: null,
  back: false,
}
