const apiValues = [
  'GAMES', 'PLAY_SESSIONS', 'PLAYER_ACTIONS',
  'GAME_1_MISSIONS', 'GAME_1_MISSION_CHARACTERS',
  'MISSIONS', 'MISSION_CHARACTER',
  'GAME_3_MISSIONS',
  'CHARACTERS', 'LOCATIONS', 'QUESTIONS', 'BACKGROUND_ASSETS',
  'QUESTIONNAIRES', 'QUESTIONNAIRE_QUESTIONS',
  'BACKGROUND_AUDIOS', 'USER_GAME_RESULTS', 'LANGUAGES' ]

export default apiValues
