const apiValues = ['CHARACTERS', 'MISSIONS', 'GAME_1_MISSIONS', 'LOCATIONS', 'QUESTIONS',
 'BACKGROUND_ASSETS', 'QUESTIONNAIRES', 'QUESTIONNAIRE_QUESTIONS', 'GAMES',
 'PLAY_SESSIONS', 'PLAYER_ACTIONS', 'BACKGROUND_AUDIOS', 'USER_GAME_RESULTS', 'GAME_1_MISSION_CHARACTERS']

export default apiValues
